# Generated by Django 4.2.16 on 2024-09-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atricle',
            new_name='Article',
        ),
    ]
